version: '2'
services:
  postgres:
    image: postgres

  omeroserver:
    image: olat/omero-test-daemon-c7:0.1.4
    links:
      - postgres
    environment:
      - SKIP_UPGRADE_CHECK=true
      - OMEROBUILD=${OMEROBUILD}
    ports:
      - 4064:4064
      - 4063:4063

  maprtest:
    image: olat/omero-test-daemon-c7:0.1.4
    links:
      - omeroserver
    environment:
      - SKIP_UPGRADE_CHECK=true
      - OMEROBUILD=${OMEROBUILD}
      - COMPONENT=server
      - RUNSCRIPT=py
      - SERVER_HOST=omeroserver
      - SERVER_PORT=4064
    volumes:
      - ../.:/home/omero/mapr.git
    command: /home/omero/mapr.git/runtest omeroserver 4064
